"""empty message

Revision ID: 9dc901c76096
Revises: c45991a7b838
Create Date: 2023-04-24 21:05:44.266840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc901c76096'
down_revision = 'c45991a7b838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_blurb'), ['blurb'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_content'), ['content'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_title'), ['title'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_title'))
        batch_op.drop_index(batch_op.f('ix_post_date'))
        batch_op.drop_index(batch_op.f('ix_post_content'))
        batch_op.drop_index(batch_op.f('ix_post_blurb'))
        batch_op.drop_index(batch_op.f('ix_post_author'))

    op.drop_table('post')
    # ### end Alembic commands ###
